language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

install:
    - travis_retry composer self-update
    - travis_retry composer install --ignore-platform-reqs
    - composer info -i

script: phpunit
