services:
    zwaan.event_handling.event_bus:
        class: Zwaan\EventSourcing\EventHandling\AsyncEventBus
        arguments: [@zwaan.event_handler]

    zwaan.event_handler:
        class: Zwaan\EventSourcing\EventHandling\RabbitMQEventHandler
        arguments: [@zwaan.rabbitmq_adapter.php_amqp_lib, @zwaan.serializer]

    zwaan.rabbitmq_adapter.php_amqp_lib:
        class: Zwaan\EventSourcing\MessageHandling\RabbitMQ\PhpAmqpLibFanoutAdapter
        arguments: [%exchange_name%, %queue_name%, @amqp_stream_connection]

    zwaan.serializer:
        class: Zwaan\EventSourcing\Serializer\PhpSerializer

    amqp_stream_connection:
        class: PhpAmqpLib\Connection\AMQPStreamConnection
        arguments: ['localhost', 5672, 'guest', 'guest']
