services:
    zwaan.event_handling.event_bus:
        class: Zwaan\EventSourcing\EventHandling\AsyncEventBus
        arguments: [@async.message_handler]

    zwaan.message_handler:
        class: Zwaan\EventSourcing\EventHandling\RabbitMQMessageHandler
        arguments: [%exchange_name%, %queue_name%, @amqp_stream_connection , @async.serializer]

    zwaan.serializer:
        class: Zwaan\EventSourcing\Serializer\PhpSerializer

    amqp_stream_connection:
        class: PhpAmqpLib\Connection\AMQPStreamConnection
        arguments: ['localhost', 5672, 'guest', 'guest']
